### ISSUE TITLE
Teach obs-to-maven about OBS project inheritance

### ISSUE THREAD

**Issue by moio** [uyuni-project/obs-to-maven#2]
## Context

OBS has a concept called inheritance, where one project comprises packages that are not part of the project itself, but rather from some other "parent".

For example, see `openSUSE:Leap:15.2:Update`:

![image](https://user-images.githubusercontent.com/250541/91581075-473b2200-e94e-11ea-9803-a133e2780769.png)

In this screenshot, there are 788 packages in the project, but many more (12392) are inherited. Within OBS, it is possible to "consume" any of the total 13180 packages from another project simply by referencing `openSUSE:Leap:15.2:Update`.

This mechanism is a big simplification, because inherited packages might come from many projects ([see this more complicated example from our internal instance](https://build.suse.de/project/show/SUSE:SLE-15-SP2:Update:Products:Manager41:Update)).

## Problem

Inherited packages are not returned by the `osc.core.get_binarylist` API endpoint `obs2maven` uses. This forces the maintainer of the YAML descriptor to know all inheritance relationships, define all inherited projects and repos, and define which project/repo each package ultimately comes from - and that can change with time.

## Idea

`obs2maven` could be made inheritance-aware and resolve the right projects/repos automatically. For example, only Leap 15.2 Updates could be defined, and packages never updated would be taken from Leap 15.2 directly. Also, when a package is first updated, no change would be needed to the YAML descriptor.

**Comment by moio** [comment]
Alternative idea: `obs2maven` could download packages from end locations, eg. http://download.opensuse.org/distribution/leap/15.2/repo/oss/noarch/ instead of (the equivalent of) `osc getbinaries`. As a bonus downloading would not require OBS credentials (but I am not sure whether that's feasible)

**Comment by moio** [comment]
cc @renner

**Comment by renner** [comment]
I believe this has actually been resolved, as `obs-to-maven` is meanwhile actually getting the packages from https://download.opensuse.org.

**Comment by cbosdo** [comment]
This is no longer relevant since `obs-to-maven` doesn't use the OBS API anymore and the repositories don't expose the parent info.
